{{- $clustername := .Values.cluster.name -}}
{{- if eq .Values.cloudprovider "azure" }}
{{- range $index, $nodepool := .Values.nodepools }}
apiVersion: rke-machine-config.cattle.io/v1
kind: AzureConfig
metadata:
  name: {{ $clustername }}-{{ $nodepool.name }}
  namespace: fleet-default
{{- if $nodepool.acceleratedNetworking }}
acceleratedNetworking: {{ $nodepool.acceleratedNetworking }}
{{- end }}
{{- if $nodepool.availabilitySet }}
availabilitySet: {{ $nodepool.availabilitySet }}
{{- end }}
{{- if $nodepool.availabilityZone }}
availabilityZone: {{ $nodepool.availabilityZone | squote }}
{{- end }}
{{- if $nodepool.clientId }}
clientId: {{ $nodepool.clientId }}
{{- end }}
{{- if $nodepool.clientSecret }}
clientSecret: {{ $nodepool.clientSecret }}
{{- end }}
{{- if $nodepool.customData }}
customData: {{- $nodepool.customData | toYaml | indent 1 }}
{{- end }}
{{- if $nodepool.diskSize }}
diskSize: {{ $nodepool.diskSize | squote }}
{{- end }}
{{- if $nodepool.dns }}
dns: {{ $nodepool.dns }}
{{- end }}
{{- if $nodepool.dockerPort }}
dockerPort: {{ $nodepool.dockerPort | squote }}
{{- end }}
{{- if $nodepool.enablePublicIpStandardSku }}
enablePublicIpStandardSku: {{ $nodepool.enablePublicIpStandardSku }}
{{- end }}
{{- if $nodepool.environment }}
environment: {{ $nodepool.environment }}
{{- end }}
{{- if $nodepool.faultDomainCount }}
faultDomainCount: {{ $nodepool.faultDomainCount | squote }}
{{- end }}
{{- if $nodepool.image }}
image: {{ $nodepool.image }}
{{- end }}
{{- if $nodepool.location }}
location: {{ $nodepool.location }}
{{- end }}
{{- if $nodepool.managedDisks }}
managedDisks: {{ $nodepool.managedDisks }}
{{- end }}
{{- if $nodepool.noPublicIp }}
noPublicIp: {{ $nodepool.noPublicIp }}
{{- end }}
{{- if $nodepool.nsg }}
nsg: {{ $nodepool.nsg }}
{{- end }}
{{- if $nodepool.openPort }}
openPort:
{{- range $i, $port := $nodepool.openPort }}
- {{ $port | squote }}
{{- end }}
{{- end }}
{{- if $nodepool.plan }}
plan: {{ $nodepool.plan }}
{{- end }}
{{- if $nodepool.privateIpAddress }}
privateIpAddress: {{ $nodepool.privateIpAddress }}
{{- end }}
{{- if $nodepool.resourceGroup }}
resourceGroup: {{ $nodepool.resourceGroup }}
{{- end }}
{{- if $nodepool.size }}
size: {{ $nodepool.size }}
{{- end }}
{{- if $nodepool.sshUser }}
sshUser: {{ $nodepool.sshUser }}
{{- end }}
{{- if $nodepool.staticPublicIp }}
staticPublicIp: {{ $nodepool.staticPublicIp }}
{{- end }}
{{- if $nodepool.storageType }}
storageType: {{ $nodepool.storageType }}
{{- end }}
{{- if $nodepool.subnet }}
subnet: {{ $nodepool.subnet }}
{{- end }}
{{- if $nodepool.subnetPrefix }}
subnetPrefix: {{ $nodepool.subnetPrefix }}
{{- end }}
{{- if $nodepool.subscriptionId }}
subscriptionId: {{ $nodepool.subscriptionId }}
{{- end }}
{{- if $nodepool.tags }}
tags: {{ $nodepool.tags }}
{{- end }}
{{- if $nodepool.tenantId }}
tenantId: {{ $nodepool.tenantId }}
{{- end }}
{{- if $nodepool.updateDomainCount }}
updateDomainCount: {{ $nodepool.updateDomainCount | squote }}
{{- end }}
{{- if $nodepool.usePrivateIp }}
usePrivateIp: {{ $nodepool.usePrivateIp }}
{{- end }}
{{- if $nodepool.vnet }}
vnet: {{ $nodepool.vnet }}
{{- end }}
---
{{- end }}
{{ $nodepool := .Values.nodepool }}
{{- if $nodepool }}
apiVersion: rke-machine-config.cattle.io/v1
kind: AzureConfig
metadata:
  name: {{ $clustername }}-{{ $nodepool.name }}
  namespace: fleet-default
{{- if $nodepool.acceleratedNetworking }}
acceleratedNetworking: {{ $nodepool.acceleratedNetworking }}
{{- end }}
{{- if $nodepool.availabilitySet }}
availabilitySet: {{ $nodepool.availabilitySet }}
{{- end }}
{{- if $nodepool.availabilityZone }}
availabilityZone: {{ $nodepool.availabilityZone | squote }}
{{- end }}
{{- if $nodepool.clientId }}
clientId: {{ $nodepool.clientId }}
{{- end }}
{{- if $nodepool.clientSecret }}
clientSecret: {{ $nodepool.clientSecret }}
{{- end }}
{{- if $nodepool.customData }}
customData: {{- $nodepool.customData | toYaml | indent 1 }}
{{- end }}
{{- if $nodepool.diskSize }}
diskSize: {{ $nodepool.diskSize | squote }}
{{- end }}
{{- if $nodepool.dns }}
dns: {{ $nodepool.dns }}
{{- end }}
{{- if $nodepool.dockerPort }}
dockerPort: {{ $nodepool.dockerPort | squote }}
{{- end }}
{{- if $nodepool.enablePublicIpStandardSku }}
enablePublicIpStandardSku: {{ $nodepool.enablePublicIpStandardSku }}
{{- end }}
{{- if $nodepool.environment }}
environment: {{ $nodepool.environment }}
{{- end }}
{{- if $nodepool.faultDomainCount }}
faultDomainCount: {{ $nodepool.faultDomainCount | squote }}
{{- end }}
{{- if $nodepool.image }}
image: {{ $nodepool.image }}
{{- end }}
{{- if $nodepool.location }}
location: {{ $nodepool.location }}
{{- end }}
{{- if $nodepool.managedDisks }}
managedDisks: {{ $nodepool.managedDisks }}
{{- end }}
{{- if $nodepool.noPublicIp }}
noPublicIp: {{ $nodepool.noPublicIp }}
{{- end }}
{{- if $nodepool.nsg }}
nsg: {{ $nodepool.nsg }}
{{- end }}
{{- if $nodepool.openPort }}
openPort:
{{- range $i, $port := $nodepool.openPort }}
- {{ $port | squote }}
{{- end }}
{{- end }}
{{- if $nodepool.plan }}
plan: {{ $nodepool.plan }}
{{- end }}
{{- if $nodepool.privateIpAddress }}
privateIpAddress: {{ $nodepool.privateIpAddress }}
{{- end }}
{{- if $nodepool.resourceGroup }}
resourceGroup: {{ $nodepool.resourceGroup }}
{{- end }}
{{- if $nodepool.size }}
size: {{ $nodepool.size }}
{{- end }}
{{- if $nodepool.sshUser }}
sshUser: {{ $nodepool.sshUser }}
{{- end }}
{{- if $nodepool.staticPublicIp }}
staticPublicIp: {{ $nodepool.staticPublicIp }}
{{- end }}
{{- if $nodepool.storageType }}
storageType: {{ $nodepool.storageType }}
{{- end }}
{{- if $nodepool.subnet }}
subnet: {{ $nodepool.subnet }}
{{- end }}
{{- if $nodepool.subnetPrefix }}
subnetPrefix: {{ $nodepool.subnetPrefix }}
{{- end }}
{{- if $nodepool.subscriptionId }}
subscriptionId: {{ $nodepool.subscriptionId }}
{{- end }}
{{- if $nodepool.tags }}
tags: {{ $nodepool.tags }}
{{- end }}
{{- if $nodepool.tenantId }}
tenantId: {{ $nodepool.tenantId }}
{{- end }}
{{- if $nodepool.updateDomainCount }}
updateDomainCount: {{ $nodepool.updateDomainCount | squote }}
{{- end }}
{{- if $nodepool.usePrivateIp }}
usePrivateIp: {{ $nodepool.usePrivateIp }}
{{- end }}
{{- if $nodepool.vnet }}
vnet: {{ $nodepool.vnet }}
{{- end }}
{{- end }}
{{- end }}
