{{- $clustername := .Values.cluster.name -}}
{{- if eq .Values.cloudprovider "harvester" }}
{{- range $index, $nodepool := .Values.nodepools }}
apiVersion: rke-machine-config.cattle.io/v1
kind: HarvesterConfig
metadata:
  name: {{ $clustername }}-{{ $nodepool.name }}
  namespace: fleet-default
{{- if $nodepool.clusterId }}
clusterId: {{ $nodepool.clusterId }}
{{- end }}
{{- if $nodepool.clusterType }}
clusterType: {{ $nodepool.clusterType }}
{{- end }}
{{- if $nodepool.cpuCount }}
cpuCount: {{ include "rancher-cluster-templates.string" $nodepool.cpuCount | squote }}
{{- end }}
{{- if $nodepool.cpuModel }}
cpuModel: {{ $nodepool.cpuModel }}
{{- end }}
{{- if $nodepool.cpuPinning }}
cpuPinning: {{ $nodepool.cpuPinning }}
{{- end }}
{{- if $nodepool.diskBus }}
diskBus: {{ $nodepool.diskBus }}
{{- end }}
{{- if $nodepool.diskInfo }}
diskInfo: {{- $nodepool.diskInfo | toYaml | indent 1 }}
{{- end }}
{{- if $nodepool.diskSize }}
diskSize: {{ include "rancher-cluster-templates.string" $nodepool.diskSize | squote }}
{{- end }}
{{- if $nodepool.enableEfi }}
enableEfi: {{ $nodepool.enableEfi }}
{{- end }}
{{- if $nodepool.enableSecureBoot }}
enableSecureBoot: {{ $nodepool.enableSecureBoot }}
{{- end }}
{{- if $nodepool.enableTpm }}
enableTpm: {{ $nodepool.enableTpm }}
{{- end }}
{{- if $nodepool.imageName }}
imageName: {{ $nodepool.imageName }}
{{- end }}
{{- if $nodepool.isolateEmulatorThread }}
isolateEmulatorThread: {{ $nodepool.isolateEmulatorThread }}
{{- end }}
{{- if $nodepool.keyPairName }}
keyPairName: {{ $nodepool.keyPairName }}
{{- end }}
{{- if $nodepool.kubeconfigContent }}
kubeconfigContent: {{- $nodepool.kubeconfigContent | toYaml | indent 1 }}
{{- end }}
{{- if $nodepool.memorySize }}
memorySize: {{ include "rancher-cluster-templates.string" $nodepool.memorySize | squote }}
{{- end }}
{{- if $nodepool.networkData }}
networkData: {{- $nodepool.networkData | toYaml | indent 1 }}
{{- end }}
{{- if $nodepool.networkInfo }}
networkInfo: {{- $nodepool.networkInfo | toYaml | indent 1 }}
{{- end }}
{{- if $nodepool.networkModel }}
networkModel: {{ $nodepool.networkModel }}
{{- end }}
{{- if $nodepool.networkName }}
networkName: {{ $nodepool.networkName }}
{{- end }}
{{- if $nodepool.networkType }}
networkType: {{ $nodepool.networkType }}
{{- end }}
{{- if $nodepool.reservedMemorySize }}
reservedMemorySize: {{ include "rancher-cluster-templates.string" $nodepool.reservedMemorySize | squote }}
{{- end }}
{{- if $nodepool.sshPassword }}
sshPassword: {{ include "rancher-cluster-templates.string" $nodepool.sshPassword | toRawJson }}
{{- end }}
{{- if $nodepool.sshPort }}
sshPort: {{ include "rancher-cluster-templates.string" $nodepool.sshPort | squote }}
{{- end }}
{{- if $nodepool.sshPrivateKeyPath }}
sshPrivateKeyPath: {{ $nodepool.sshPrivateKeyPath }}
{{- end }}
{{- if $nodepool.sshUser }}
sshUser: {{ $nodepool.sshUser }}
{{- end }}
{{- if $nodepool.userData }}
userData: {{- $nodepool.userData | toYaml | indent 1 }}
{{- end }}
{{- if $nodepool.vgpuInfo }}
vgpuInfo: {{- $nodepool.vgpuInfo | toYaml | indent 1 }}
{{- end }}
{{- if $nodepool.vmAffinity }}
vmAffinity: {{- $nodepool.vmAffinity | toYaml | indent 1 }}
{{- end }}
{{- if $nodepool.vmNamespace }}
vmNamespace: {{ $nodepool.vmNamespace }}
{{- end }}
---
{{- end }}
{{- end }}
